name: Get latest Cardano Node tag
on:
  schedule:
    - cron: '0 */16 * * *'
  workflow_dispatch:

jobs:
  get-latest-cardano-node-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout input-output-hk/cardano-node
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
          repository: 'input-output-hk/cardano-node'

      - name: Get Latest Tag of cardano-node
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: previoustag

      - name: Checkout the local repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Apply latest tag to file
        run: |
          export VERSION=${{ steps.previoustag.outputs.tag }}
          if ! [ -d "${VERSION}" ] ; then 
            mkdir ${VERSION}
          else
            echo "Directory ${VERSION} already exists"
          fi
                  
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        
      - name: Commit latest tag version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name ${{ secrets.REPO_SCOPED_USER }}
          git config --global user.email ${{ secrets.REPO_SCOPED_EMAIL }}
          git commit -am "New cardano-node master tag ${VERSION}"
          git push
